# Generated by Django 4.2.7 on 2026-04-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebill',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('mixed', 'Cash & Card'), ('cash_upi', 'Cash & UPI')], max_length=10),
        ),
    ]
