# Generated by Django 4.2.7 on 2026-04-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_salebill_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebill',
            name='upi_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('cash_card', 'Cash & Card'), ('cash_upi', 'Cash & UPI')], max_length=10),
        ),
    ]
