# Generated by Django 4.2.7 on 2026-04-16 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_internalsalemaster_internalsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='selling_unit',
            field=models.CharField(choices=[('nos', 'Nos'), ('kg', 'Kg'), ('carton', 'Carton')], default='nos', max_length=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_unit',
            field=models.CharField(choices=[('nos', 'Nos'), ('kg', 'Kg'), ('carton', 'Carton')], default='nos', max_length=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='selling_unit',
            field=models.CharField(choices=[('nos', 'Nos'), ('kg', 'Kg'), ('carton', 'Carton')], default='nos', max_length=10),
        ),
        migrations.AlterField(
            model_name='internalsale',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='damaged_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='expired_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='api.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.purchasebill'),
        ),
    ]
