# Generated by Django 4.2.7 on 2026-04-16 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_vendor_product_selling_unit_purchase_purchase_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='selling_qty',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='api.product')),
            ],
        ),
    ]
